language: node_js
matrix:
  include:
  - node_js: '4'
    env:
    - UNIT=test:harmony
  - node_js: '5'
    env:
    - UNIT=test:harmony
  - node_js: '6'
    env:
    - UNIT=test
  - node_js: '7'
    env:
    - UNIT=test
  - node_js: '8'
    env:
    - UNIT=test
  - node_js: node
    env:
    - UNIT=test
env:
  global:
    - CC_TEST_REPORTER_ID=4ec83f1d841acdd74d7b402ee6502e15a12fcc882e09f732cbf859a2c1c595f4
    - NODE_ENV=testing
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run $UNIT
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  slack:
    secure: idZySEFjzRjO1jbvuYf/uQ16Qq/kWR6rvq202y1IGzXsVrvGReoSvB5B1tRf0JkacHQFwOd/zn6qfvmlUA9ItpAkWg+ZNHooNDlrOxjkqPUEKF0K70HrKUDfkqAQwJy9tzrFD4YYRw01jm7/NPuLu/H0VQ9zdOpIviNUpI916wgKJOQSk/X70pzl+8FGo8DDSmeM7tfYcFt/WtBeRzINeVQKnzOU8IhEiJUB1uoud/i0ntOnJyRtnckAyrTiZeiZOmNWmdeNJX0R3Np+eBoKM641/vFqQZmnLBUnw1pUVleiH4lYzBGaVNLgJdEPbaPP12+wDwTDKT70YcBnTFbAuTx66TVIl39aJQlvfQp8+6NKpFc5FnvqWtxx0VN7MidzikIiFz/6IWi7+G0lhn4Suoev0rFsh39Z7dWSSd7YwNmEPgs9OWyHZicuAobyE7C9W/sJ9ZSvt2wSGU9lXuyrcIDX1GbGKDyqmcqeTDOK0pEvyrL3GI/P7yfqWe7TyEV7pcwC58HT6yWueCj86JIA7IE3/+o+U6zNORd3ySKYmWHjw5fPz8HFDYeUS1kDbJYIXsX28ZQVExOQW0FIhIoDoH95v7K4dS41190sx6VCpQLvPIQqm+yvl90Qk8DEw/NxJY6CFOjVeI5Ao5ofUWtmzYQ36EH5M05BScg/mp+HKCI=
