language: node_js
matrix:
  include:
  - node_js: '6'
    env:
    - UNIT=test
  - node_js: '7'
    env:
    - UNIT=test
  - node_js: '8'
    env:
    - UNIT=test
  - node_js: '9'
    env:
    - UNIT=test
  - node_js: node
    env:
    - UNIT=test
env:
  global:
  - NODE_ENV=testing
  - secure: VyvQ0x0TyBHLJgHHxwYtk1o3bnAdge2wwoFnJN5/jqP1IQPHzjpDkqYErg4AzObRD9dGmw5D3/tZB9B7k2GMsJkX5HMjBoOCqxMhhCOkC7p6eFsFpv7gYTfGgeGAcHailfLLkH+oi7Qc3+XL/EDzWK0ES9c3RR0DxfMSbiiqbaKNwiAYjIh9Bp/6D66G14O35e61dV6bFDqb0WM6CnhVWyYc6beFz4eZOrMM60USShfE72vabkMer4pKozx0tKJBNYqDz0HcPJd8ET1oGm8RD0Ccuxf/cijOS1El+wPsOySPBXWZwVbYW/aD2g47MQM+y79IrK68TflISiQZOAPy7ie57G7PfbBt16K/EjtC1ecx3Usf3QWeNrydPOtzp2+Aj/ElKogSt0fuVd39wSGmA2QwKqdvTUbzNvXFi1XpjfbbCP3hM4Le5jaG8zexICSNyMJBKvR5/IEWdmbtcLiPRx+WV1ckuQvgeVExanAWhqfmXnFyGsyarVn9zmTl0f3z931g9s4+kO31kt88C6QDBlM6jeTLxeccdQe0PinsQKk5wubpaF9tmdg/zHyXYiYB0dbgO6ApCpF5/WM7bs2Lgb8L810xyukm6CYTK7CqcMDKzBE5UVBf4K9mR28KX8RaRFc8WcbYpsd/HsUGDyf83DbndOHvKbesY5ZZFF7Bnl0=
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- npm run $UNIT
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
notifications:
  slack:
    secure: Ts7NvAOpVXIDq4B2W+s6MBfTOG1vW3UGxT3OPQ1k90Jfd6hzeA1nVWft+md0VBcEVQffATZGVyqlLfSGI5TMZTg+byYAw11emvQbvSkgvqWhQyFxVuCNoEQQWLZdk4SWVaizpBypzpY29piBq2LkHy7FoWA5/hFPydChfjRQjb68TKHBzOnDvtr8XZiMIZIyIQDxtAVhE5sO37ta7TRPoS0HJHRdZwtUeFRn0zYLxDb3kFXvnkziR0rEL4vS7ZWlLK7eEVRKTXWUwvyuYID7LjytWQZLCw6Vmj7Fz+EM9r7WA0RFj8jZEJ2+adGYMPLvyuvjtoVY1lxehaeIJiRvm2lNO3F1G85G+OS71Qth6XlGF1FCld2oXhrvx73r6nmovsEFsqS+lN9ajB5kNvi4npzmIbYAtx0n7ZUovMHTMhLNRfdCw51L72ABGYZDb0rsZTKFLUokBmuFAGFQBkwrlwDy1qG5C0Ak2MYHUTwYxt+u1RoHqvRyubeHUIQZk028zF93JB5OKyEhNHeR0xpr0B5j5/VUMFIR66x5S/QHEgG9kUVUDa/xBm9ZsV19DyxxnohzbqtFP6MHA/qKO9JdBQEQRNH7QhY1k0IMqr7v99GjtgZsjY6H6Mb4zB1TQ+IlM9mfLlsOmiDo+IqFJ9j7XhxD90UZpvcDpK0uxz49Xko=
deploy:
  provider: npm
  email:
    secure: ki05ah3IKBoxbwZjxXlCUKbiSOBgZwe83V5TPXHot7xupMaM5VnojM7Ud2w7ixOAHl62wtOasoJasDjn1n1X/vUyLNB3dTQt1YRuRnWFIg7XUngwbb4i9OSRExas0JLmqL7diYbw3IXWEKdSZTOoGXUuPgRsbTtycHmkTlxQKOy0aL5lbVq0YkeoCSoxcEs1TnOZ3szVr9L+aXortXfR9meSUwE1lklKJNCBSN0M8yMIOMMsmoxft5QUFAkxxA/7XEEqOXgiPKvAApLVHVUQ+DjweKPozgNL3Z1oEEtGJtFOh/JPyhrIHDrK+0MznedIr5n98EQ+jxteytRwoMio+XvvUVTNWY4TIx9p8UnLXG8YbzABf7teNFUgW89Y+syjAPi+zjuzV5BhHYhmT0gA95AXF4DNK5q1PslkIOxw2gHY3bgAPOxWquLY/wBSHDJ5fpiaWralc+3iUw2vmYB3l3OUKBiU/nNkOPSyl55U3FlaFxPo5Ty3dZ0M2Md5tQcvtFSjuocOCVmjVyvlP3IhLkcBS+m7HonQUWZj/+HsbLg07VYXK2UnMSiTCk7s7wcjReP9rGM5m5Jhdn+SFZlmjolcDmeD6/AC2jRyjxjidHnu7AY6HHJaBl4zlw+nwi1msYU8Z7yReHWsRHuvlM/dXpTfhi28avGqWId0lI1ecxw=
  api_key:
    secure: Av7S5IKbP5c1GGueV/NP/x95YS9+i0QhU8h+dNa06ejlZ9LA6Wo+4huCvnbwlFJLQT/p3LgzR7extCI38berGxWuMJGwhEVjvJyJYJOGvxhLpKdl0DagHE+9xJwRh0Nb8MrkPzWq2rZ+arjqIVqxM1TMnAyagC1fQXYvvjJ80EUr4CyuOIAYuoBPZONptF4RWSaPL3q/C96E19hsJaDQr31dvMsBCgImIZ9A3lMpRgkqH/7SnQmjuXzfx4N+OMkAep3hFRF18B1T8mJZR61P0BU5rXDnHWAt3gde8c8DxNJBTEB0HybimTs5lfm6DT4k4uPXXbn4ZPjyg7XJvi//byQ7ZyL/v5BuX8jRlgmf/5AE3wRXlk04z1gWycKj84SuZojXne9Vp7BRZsaQ9istVjWo7m8qDrnzBK0FNSdR5GnCQor8cZUcXk/AzAwyenDvCnTHV3NWTpL3QhTtrC66XFFtAOC7gAF27LdnGGYm+oQw7OoCEGvTcz7C1bmYi7ZA0SuLG89I9lSP2Wmsrwb31bYcvI72aNF99DjY+6z2F2US0/7hQ5YmoOGZHQp586IBEoqJFJfrA12zMR0ENzcZZhAUGT3QlKXD64Sb5gplKbuDPXvVvpi9Eye/UBFY0UQkXzsV3+Vkj8UpKyYXvTECSwEZdXoE7svZuHpFFx1v3hE=
  on:
    tags: true
